apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  rhtap/gitops: dotnot 
  janus-idp.io/tekton: dotnot
  backstage.io/kubernetes-id: dotnot
  backstage.io/kubernetes-namespace: rhtap-app 
  app.kubernetes.io/part-of: dotnot
resources: 
- application-dev.yaml 
- application-stage.yaml 
- application-prod.yaml  