apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  argocd/app-name: dotnot
  janus-idp.io/tekton: dotnot
  backstage.io/kubernetes-id: dotnot
  backstage.io/kubernetes-namespace: rhtap-app 
  app.kubernetes.io/part-of: dotnot
resources:
- deployment.yaml
- route.yaml
- service.yaml
