apiVersion: v1
kind: Service
metadata: 
  labels: 
    app.kubernetes.io/instance: dotnot
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: dotnot 
  name: dotnot
spec:
  ports:
  - port: 8081 
    targetPort: 8081 
  selector:
    app.kubernetes.io/instance: dotnot 
